---
- name: Setup inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Fetch EC2 IP from Terraform output
      shell: terraform output instance
      register: ec2_instance_ip

    - name: Generate Ansible Inventory
      copy:
        content: |
          [ec2_instances]
          ec2_instance ansible_host={{ ec2_instance_ip.stdout }} ansible_user=ubuntu ansible_ssh_private_key_file=project1.pem
        dest: $WORKSPACE/inventory.ini

- name: Disable SSH host key checking
  hosts: localhost
  become: yes
  tasks:
    - name: Add line to disable SSH host key checking in ansible.cfg
      lineinfile:
        path: /etc/ansible/ansible.cfg  
        line: "host_key_checking = False"
        insertafter: "[defaults]"
